### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by supercoolandinteresting** [motanelu/macvim-configuration#1]
![image](https://cloud.githubusercontent.com/assets/19422698/15476008/79dfdc0a-212a-11e6-9624-c2d795f1de4a.png)

Why are these black lines appearing?

**Comment by motanelu** [comment]
Which ones? The horizontal one is the current line you're on and the vertical one is the color column, if your coding standard specifies a line length to not go beyond it.

**Comment by supercoolandinteresting** [comment]
Thank you, understood it, could you please tell why the autocomplete isn't working?
